apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: NG_APP_API_URL
              value: {{ .Values.app.apiUrl }}
            - name: NG_APP_GRAPHQL_URL
              value: {{ .Values.app.graphQlUrl }}

          volumeMounts:
            - name: ngx-env-volume
              mountPath: /usr/share/nginx/html/ngx-env.js
              subPath: ngx-env.js
      volumes:
        - name: ngx-env-volume
          configMap:
            name: {{ include "common.names.fullname" . }}
            items:
              - key: ngx-env.js
                path: ngx-env.js