apiVersion: v2
name: openfilz-api
description: A Helm chart for deploying the OpenFilz Document Management API.
version: 2.0.0
appVersion: "latest"

dependencies:
  - name: common
    version: "2.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    # The 'common' chart is used for standardized helpers and labels.

sources:
  - https://github.com/openfilz/openfilz-core
