{{/*
Render a PersistentVolume for manual provisioning when not on OpenShift.
*/}}
{{- if and .Values.persistence.enabled (not .Values.openshift.enabled) (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pv" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
{{- end }}