{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-credentials" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.database.createUser | b64enc | quote }}
  password: {{ .Values.database.createPassword | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}