{{- if .Values.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openfilz-api.fullname" . }}-extra-env
  labels: {{- include "openfilz-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
