{{- if and (eq (include "openfilz-api.ingressEnabled" .) "true") (not .Values.openshift.enabled) .Values.ingress.swagger.enabled }}
{{- $host := include "openfilz-api.hostApi" . }}
{{- $tlsSecret := include "openfilz-api.ingressTlsSecret" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openfilz-api.fullname" . }}-swagger
  labels: {{- include "openfilz-api.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with (include "openfilz-api.ingressClassName" .) }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if and $host $tlsSecret }}
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ $tlsSecret }}
  {{- end }}
  rules:
    - {{- if $host }}
      host: {{ $host }}
      {{- end }}
      http:
        paths:
          - path: /swagger-ui.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "openfilz-api.fullname" . }}
                port:
                  name: http
          {{- range tuple "/v3/api-docs" "/swagger-resources" "/webjars" }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "openfilz-api.fullname" $ }}
                port:
                  name: http
          {{- end }}
{{- end }}
