{{- if and (eq .Values.storage.type "local") (not .Values.storage.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openfilz-api.fullname" . }}-storage
  labels: {{- include "openfilz-api.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.persistence.accessModes | nindent 4 }}
  {{- with .Values.storage.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
{{- end }}
