package org.openfilz.dms.enums;

public enum AuditAction {
    COPY_FILE,
    COPY_FILE_CHILD,
    RENAME_FILE,
    RENAME_FOLDER,
    COPY_FOLDER,
    DELETE_FILE,
    DELETE_FILE_CHILD,
    DELETE_FOLDER,
    CREATE_FOLDER,
    MOVE_FILE,
    MOVE_FOLDER,
    UPLOAD_DOCUMENT,
    REPLACE_DOCUMENT_CONTENT,
    REPLACE_DOCUMENT_METADATA,
    UPDATE_DOCUMENT_METADATA,
    DOWNLOAD_DOCUMENT,
    DELETE_DOCUMENT_METADATA,
    SHARE_DOCUMENTS
}
